on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*.*"
  pull_request:

jobs:
  build-and-push:
    name: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: "[STEP] Checkout"
        uses: actions/checkout@v2

      - name: "[STEP] Setup pipeline environment variables"
        run: |
          echo "::set-env name=MY_GIT_SHA::$(git rev-parse --short "$GITHUB_SHA")"
          echo "::set-env name=MY_IMAGE_TAG::${GITHUB_REF#refs/*/}"

      - name: "[STEP] Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: "[STEP] Login to Amazon ECR"
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr

      - name: "[STEP] Build Docker image and push to Amazon ECR"
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: simple-microblog-service
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "::set-env name=ECR_REGISTRY::$ECR_REGISTRY"

          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$MY_GIT_SHA .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:"$MY_GIT_SHA"
