version: "3.5"

services: 
  {{@root.swagger.info.x-snc-template-config.docker.image-name}}:
    env_file:
      - ./.env-template
    build:
      context: .
      args:
        environment: "development"
    volumes:
      - ./:/app
    ports:
      - "8081:8080"
    networks:
      - shared_network
networks:
  shared_network:
    name: "shared"

